using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class DialogueManger2 : MonoBehaviour
{

    public GameObject dBox;
    public Text dText;
    public int number = 0;

    public bool dialogActive;

    public string[] dialogLines;
    public int currentLine;

    public bool canmove;
    // Use this for initialization
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        if (dialogActive && Input.GetKeyDown(KeyCode.Space))
        {
            //dBox.SetActive(false);
            //dialogActive = false;

            currentLine++;
        }

        if (currentLine >= dialogLines.Length)
        {
            dBox.SetActive(false);
            dialogActive = false;
            currentLine = 0;
            canmove = false;

        }

        dText.text = dialogLines[currentLine];
    }

    public void ShowBox(string dialog)
    {
        dialogActive = true;
        dBox.SetActive(true);
        dText.text = dialog;
        canmove = true;
    }
}
